services:
  stats-server:
    build:
      context: ./stats-service/stats-server
      dockerfile: Dockerfile
    image: ewm-stats-server:latest
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "cat < /dev/tcp/localhost/9090 >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  ewm-service:
    build:
      context: ./ewm-main-service
      dockerfile: Dockerfile
    image: ewm-main-service:latest
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      stats-server:
        condition: service_healthy
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_SERVER_URL=http://stats-server:9090